### ISSUE TITLE
报错：navigating to "", waiting until "load"

### ISSUE THREAD

**Issue by mayjack0312** [kerm-me/docdown#17]
```
PS C:\WINDOWS\system32> cd
PS C:\WINDOWS\system32> cd C:\Users\Desktop\docdown-1.1.0
PS C:\Users\Desktop\docdown-1.1.0> ./docdown 'https://max.book118.com/html/2022/1028/6113124131005010.shtm'
您可以直接访问PPT预览（无广告）：
https://view41.book118.com/?readpage=jDA0r@OLdvjWvcxa0TKXsQ==&furl=c0LZaqbditkfo3Mn_ZthAeCN86wcDVAMFcwHXsMVYHJtg27mBxWPCRGee0YeQxh9NyNl0gM8pactvnE1TwnN11DXLFTQGzZbJDOxY2rxS_M=&n=1
invalid literal for int() with base 10: ''
下载PPT失败，请至GitHub提交issue，附上下载链接
下载失败，请注意关闭代理，如果还有问题，请至GitHub提交issue，附上下载链接
PS C:\Users\Desktop\docdown-1.1.0> ./docdown 'https://max.book118.com/html/2022/1028/6113124131005010.shtm'
您可以直接访问PPT预览（无广告）：

Protocol error (Playwright.navigate): Cannot navigate to invalid URL [{"code":-32000,"message":"Cannot navigate to invalid URL"}]
=========================== logs ===========================
navigating to "", waiting until "load"
============================================================
下载PPT失败，请至GitHub提交issue，附上下载链接
下载失败，请注意关闭代理，如果还有问题，请至GitHub提交issue，附上下载链接
PS C:\Users\Desktop\docdown-1.1.0>
```
文档下载链接：https://max.book118.com/html/2022/1028/6113124131005010.shtm

**Comment by Alitterman** [comment]
可以尝试下源码运行

> 直接运行源码
克隆本项目，安装依赖

pip install -r requirements.txt

# 安装playwright库
pip install playwright

# 安装浏览器驱动文件（安装过程稍微有点慢）
python3 -m playwright install

# 或者（如果上面命令报错）
playwright install

**Comment by mayjack0312** [comment]
> 

直接源码运行也还是报错
```
C:\Users>f:
F:\>cd F:\githome\docdown-1.1.0
F:\githome\docdown-1.1.0>python run.py 'https://max.book118.com/html/2022/1028/6113124131005010.shtm'
Traceback (most recent call last):
  File "F:\githome\docdown-1.1.0\run.py", line 6, in <module>
    tool.download_from_url(url)
  File "F:\githome\docdown-1.1.0\tool.py", line 121, in download_from_url
    page.goto(url)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 8114, in goto
    self._sync(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 146, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 396, in wrap_api_call
    return await cb()
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Playwright.navigate): Cannot navigate to invalid URL [{"code":-32000,"message":"Cannot navigate to invalid URL"}]
=========================== logs ===========================
navigating to "'https://max.book118.com/html/2022/1028/6113124131005010.shtm'", waiting until "load"
============================================================
F:\githome\docdown-1.1.0>
```
报错返回结果好像还是 `waiting until "load"`

**Comment by Alitterman** [comment]
> 

你这个原因是网速慢没加载出来，我已经有一个提交了，新合并申请无法完成，你可以直接访问我的仓库拉代码https://github.com/Alitterman/docdown

**Comment by mayjack0312** [comment]
> > 
> 
> 你这个原因是网速慢没加载出来，我已经有一个提交了，新合并申请无法完成，你可以直接访问我的仓库拉代码https://github.com/Alitterman/docdown 加了个参数等待时间 下面是样例 python run.py 'https://max.book118.com/html/2017/1105/139064432.shtm' [sleeptime] python run.py 'https://max.book118.com/html/2017/1105/139064432.shtm' 1 等待时间可以试试调大点

好滴，谢谢大佬，费心了(*^▽^*)

**Comment by tmeppp** [comment]
我发现Windows下是网址的单引号的问题，单引号会被原封不动传入程序，导致网址访问出错，双引号会被cmd自动去掉不会有问题

**Comment by mayjack0312** [comment]
> 我发现Windows下是网址的单引号的问题，单引号会被原封不动传入程序，导致网址访问出错，双引号会被cmd自动去掉不会有问题

搜嘎，学到了 谢谢大佬
